// <auto-generated />
using System;
using FridgeProduct.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FridgeProduct.Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20211229213413_addInitData")]
    partial class addInitData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FridgeProduct.Entities.Models.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FridgeId");

                    b.Property<Guid?>("FridgeModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FridgeModelId");

                    b.ToTable("Fridges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b104622-4fef-465a-a5d4-2015de2c7090"),
                            ModelId = new Guid("745cff18-3dfe-4c44-8eb9-5bd6c3e8f328"),
                            Name = "Holod",
                            OwnerName = "Aleks"
                        },
                        new
                        {
                            Id = new Guid("7b104622-4fef-465a-a5d4-2015de2c7091"),
                            ModelId = new Guid("745cff18-3dfe-4c44-8eb9-5bd6c3e8f328"),
                            Name = "Holodilnik",
                            OwnerName = "Loser"
                        },
                        new
                        {
                            Id = new Guid("5df63d42-598e-4b30-8493-8fd0c6cdaf18"),
                            ModelId = new Guid("41914da1-1deb-47d2-bf06-92e71952b7d4"),
                            Name = "Moroz",
                            OwnerName = "Viktor"
                        });
                });

            modelBuilder.Entity("FridgeProduct.Entities.Models.FridgeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModelId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FridgeModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65afe2b1-27ac-4657-865c-065d10505bef"),
                            Name = "NewModelOne",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("ce82a987-8381-43c1-9dae-c1181da0510f"),
                            Name = "NewModelTwo",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("FridgeProduct.Entities.Models.FridgeToProduct", b =>
                {
                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.HasKey("FridgeId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("FridgeToProduct");

                    b.HasData(
                        new
                        {
                            FridgeId = new Guid("7b104622-4fef-465a-a5d4-2015de2c7090"),
                            ProductId = new Guid("962be0f6-a4a3-4e17-bf3e-1ea1b7e029d3"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("FridgeProduct.Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<int>("DefaultQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductName");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("962be0f6-a4a3-4e17-bf3e-1ea1b7e029d3"),
                            DefaultQuantity = 1,
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = new Guid("14ad7a49-95f6-4e96-9c29-c3080ec493d0"),
                            DefaultQuantity = 1,
                            Name = "Bacon"
                        });
                });

            modelBuilder.Entity("FridgeProduct.Entities.Models.Fridge", b =>
                {
                    b.HasOne("FridgeProduct.Entities.Models.FridgeModel", "FridgeModel")
                        .WithMany("Fridges")
                        .HasForeignKey("FridgeModelId");

                    b.Navigation("FridgeModel");
                });

            modelBuilder.Entity("FridgeProduct.Entities.Models.FridgeToProduct", b =>
                {
                    b.HasOne("FridgeProduct.Entities.Models.Fridge", "Fridge")
                        .WithMany("FridgeToProducts")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FridgeProduct.Entities.Models.Product", "Product")
                        .WithMany("FridgeToProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FridgeProduct.Entities.Models.Fridge", b =>
                {
                    b.Navigation("FridgeToProducts");
                });

            modelBuilder.Entity("FridgeProduct.Entities.Models.FridgeModel", b =>
                {
                    b.Navigation("Fridges");
                });

            modelBuilder.Entity("FridgeProduct.Entities.Models.Product", b =>
                {
                    b.Navigation("FridgeToProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
